server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_ranking_user
    username: root
    password: Asad@123mysql

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format-sql: true	
  config:
    import: configserver:http://localhost:8085

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints: 
    web: 
      exposure:
        include: health

  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      userRatingHotelBreaker: 
#        registerHealthIndicator: true
#        eventConsumerBufferSize: 10
#        failure-rate-threshold: 50
#        minimum-number-of-calls: 5
#        automatic-transition-from-open-to-half-open-enabled: true
#        wait-duration-in-open-state: 6s
#        permitted-number-of-calls-in-half-open-state: 3
#        sliding-window-size: 10
#        sliding-window-type: count-based
#         record-exceptions:
#          - java.lang.IllegalStateException
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: count-based

        recordExceptions:
          - java.lang.IllegalStateException
  retry:
    instances:
      ratingHotelService:
        max-attempts: 3
        wait-duration: 2s
  ratelimiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 0s


#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka